openapi: 3.0.3
info:
  title: Maturity Model Specification
  description: |-
    Simple maturity model standard model and API.
    
    Concepts:
      - Maturity Model: Is a set of indicators. For instance, a maturity model may measure how mature is an organization in terms of digital dexterity.
      - Indicator: is a property that whose maturity is going to be evaluated. For instance, following the example of digital dexterity, an indicator may be the use of word processor advanced features within the organization 
      - Maturity Levels: Represent the different maturity states available in the maturity model. Typically Maturity models use three levels or maturity: Low, Medium, High or Level 1, Level 2 and Level 3. 
      - Indicator Maturity Level: For each indicator, it indicates what are the conditions required in order to achieve that level of maturity. For example, for the indicator "use of word processor advanced features", the maturity level 1 can be defined as "less than 33% of the users of the organization have ever used the automatic index in a word document".
      - Maturity Evaluation: Is the evaluation under a maturity model for a particular entity. For example, when the digital dexterity maturity model is used to evaluate an organization such as UNICEF.
      - Indicator Evaluation: Is the level or levels that are assigned in a particular entity for a particular indicator within an evaluation. For example, the evaluation of the indicator "user of word processor advanced features" within UNICEF is level 3.
      
   
#  termsOfService: http://pending.com
  license:
    name: Creative Commons 4.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
externalDocs:
  description: Find out more about this
  url: http://github.com/merlos/maturity-model-spec
tags:
  - name: Models
    description: Models
    externalDocs:
      description: Find out more
      url: http://swagger.io
  - name: Evaluations
    description: Access to evaluation items
    externalDocs:
      description: Find out more about our store
      url: http://swagger.io

paths:
  /maturitymodels:
    put:
      tags:
        - pet
      summary: Update an existing model
      description: Update an existing maturity model by code
      operationId: updatePet
      requestBody:
        description: Update an existent maturity model in the store
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MaturityModel'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/MaturityModel'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MaturityModel'
            application/xml:
              schema:
                $ref: '#/components/schemas/MaturityModel'
        '400':
          description: Invalid ID supplied
        '404':
          description: Pet not found
        '405':
          description: Validation exception


components:
  schemas:
    MaturityModel:
      description: |- 
        A maturity model is a set of indicators. 
        Each indicator has different levels of maturity. 
        The way indicators can be selected is defined by the type of mode
          - Unilevel, means that only one level can be selected. For example, if the for each indicator the levels of maturity are Low, Medium and High, it means that only one of them can be selected.
          - Multi level means that an indicator may have selected more than one level at a time. Which means that each level is independent. For example, if for an indicator there are two levels, such as Level A and Level B, it means that any of them can be achieved independently.
        
      type: object
      properties:
        code: 
          type: string
          example: "MM01"
          description: "A short string identifier. Once assigned it should not be modified. It is used as external reference for the evaluation."
        name: 
          type: string
          example: "Digital Resilience Maturity Model"
        varsion: 
          type: integer
          example: 1
          description: "Numeric version of the maturity model. It is used to keep track of the compatibility."
        indicators:
          type: array
          items: 
            $ref: "#/components/schemas/Indicator"  
          uniqueItems: true
        indicatorMode:
          description: "Unilevel means that only one indicator can be selected. Multilevel more than one indicator can be selected"
          type: string
          enum:
            - UniLevel
            - MultiLevel
          default: UniLevel
          nullable: true
        maturityLevels:
          type: array
          items:
             $ref: "#/components/schemas/MaturityLevel"  
    
    MaturityLevel:
      description: |- 
        Each possible indicator value belongs to a level
      type: object
      properties:
        id: 
          type: integer
        name: 
          type: string
          example: "Level 1"
        description: 
          type: string
          example: "Lowest value"
        weight: 
          description: Weight of the level 
          type: number
          default: 1.0  
    

    IndicatorCategory:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name: 
          type: string
        attributes:
          type: array
          items:
             $ref: '#/components/schemas/Attribute'
    
    Attribute:
      type: object
      properties:
        id:
          type: integer
          format: int64
        category:
          $ref: '#/components/schemas/IndicatorCategory'
          
    Indicator:
      description: |-
        A maturity model is a list of indicators. Each indicator has a set of levels of compliance. For example an indicator can be "Information Security Awareness training".
        A indicator belongs to a particular level. 
        To calculate the weight of the indicator = 
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        code:
          type: string
          example: "DP-LF"
          nullable: true
        name:
          type: string
          example: "Legitimate and Fair"
        shortDescription:
          type: string
          example: |-
            As part of the business analysis, requirement decisions it is ensured that personal  data collected for the limited specified purposes has a legitimate base that supports it.
        
        weight: 
          type: number
          default: 1.0  
          
        indicatorMaturityLevels:
          type: array
          items:
             $ref: '#/components/schemas/IndicatorMaturityLevel'
          description: |- 
            Each indicator has a set of maturity levels, f.i. level 1, level 2, level 3.
            Each level has a description that formulates what are the requirements 
            in order to comply with it.
        categories:
          type: array
          items: 
             $ref: '#/components/schemas/Attribute'  
    
    
    IndicatorMaturityLevel:
      type: object
      properties: 
        code: 
          type: string
          example: "Ind1-Lev1"
        maturityLevel:  
          $ref: '#/components/schemas/MaturityLevel'
        description:
          type: string
          example: "In order to comply with this level on this indicator A, B and C are in place."
          description: "The description explains what are the requirements that for this indicator, the item evaluated needs to comply with."
        
    MaturityEvaluation:
      description: |-
        Defines the values of a particular instance of a model. For example, if the 
        maturity model evaluates the maturity of an application in terms of security processes and best practices, it would provide the maturiy of that especific application.
      type: object
      properties:
        id: 
          type: integer
        name: 
          description: |- 
            Name of the product/item that is going to ve evaluated against the maturity model
          type: string
        description:
          type: string
          description: "Some overall comment about the state of this evaluation"
          nullable: true
        maturityModelCode:
          type: string
          description: "Code of the maturity model"
        selectedIndicators:
          description: |-
            List of the selected indicators. 
          type: array
          items:
            $ref: '#/components/schemas/IndicatorEvaluation'
         
    IndicatorEvaluation: 
      type: object
      properties:
        id: 
          type: integer
          format: int64
        maturityEvaluationId:
          type: integer
          format: int64
          description: "Reference to the maturity evaluation this indicator evaluation belongs to"
        indicatorCode:
          type: string
          example: "DP-LF"
          description: "The code of the indicator that is being evaluated"
        applies: 
          description: |-
            Does the indicator apply for this particular evaluation?
          type: boolean
          default: true
        comment: 
          description: |-
            Overall optional comment about the compliance with the indicator
          type: string
          nullable: true
        SelectedLevels:
          type: array
          items:
            $ref: '#/components/schemas/SelectedLevel'
          description: "What is or are the selected levels for this indicator."
          
    
    SelectedLevel:
      type: object
      description: |-
        For a particular indicator and for the evaluation of the maturity of a particular item, it represents the maturity levels that apply. 

      properties:
        maturityModelValueCode: 
          description: "Instance of a particular maturity model"
          type: string
        indicatorCode:
          description: "instance of a particular indicator in a particular maturity model"
          type: integer
          format: int64
        indicatorEvaluationId:
          description: id of the selected indicator
          type: integer
          format: int64
        isSelected:
          description: Is the level selected?
          type: boolean
          default: false
          
          
