openapi: 3.0.3
info:
  title: Maturity Model Specification
  description: |-
    Simple maturity model specification data model and API.
#  termsOfService: http://pending.com
  license:
    name: Creative Commons 4.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
externalDocs:
  description: Find out more about this
  url: http://github.com/merlos/maturity-model-spec
tags:
  - name: Models
    description: Endpoints to manage the definition of the Maturity Models
#    externalDocs:
#      description: 
      
  - name: Evaluations
    description: Endpoints to manage the evaluations against the maturity models
#    externalDocs:
#      description: Find out more about our store
#      url: http://swagger.io

paths:
  /models:
    get: 
      tags:
        - Models
      summary: Gets the list of existing maturity models
      description: Gets the list of existing maturity models in the database
      operationId: getAllModels
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MaturityModelList'
        '400':
          description: Invalid ID supplied
        '404':
          description: No models found
        '405':
          description: Validation exception
    post: 
      tags: 
        - Models
      summary: Create a new model
      description: Creates an existing maturity model.
      operationId: createModel
      requestBody:
        description: Update an existent maturity model in the store
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MaturityModel'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MaturityModel'
            application/xml:
              schema:
                $ref: '#/components/schemas/MaturityModel'
        '400':
          description: Invalid ID supplied
        '404':
          description: Pet not found
        '405':
          description: Validation exception
   
  
  /models/{code}:
    get:
      tags:
        - Models
      summary: Gets an specific maturity model by code
      description: |-
        Gets a complete maturity model by code.
        
      operationId: getModel
      parameters:
        - name: code
          in: path
          description: Code of the maturity model to be returned
          required: true
          schema:
            type: string
            pattern: '[a-zA-Z0-9\-\.\_]+'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MaturityModel'
        '400':
          description: Invalid Code supplied
        '404':
          description: Maturity model not found
        '405':
          description: Validation exception
    put:
      tags: 
        - Models
      summary: Update an existing model
      description: Update an existing maturity model by code
      operationId: updateModel
      parameters:
        - name: code
          in: path
          description: Code of the maturity model to be returned
          required: true
          schema:
            type: string
            pattern: '[a-zA-Z0-9\-\.\_]+'
      requestBody:
        description: Update an existent maturity model in the store
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MaturityModel'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MaturityModel'
        '400':
          description: Invalid ID supplied
        '404':
          description: Maturity models not found
        '405':
          description: Validation exception
#      externalDocs:
#        description: Learn more about user operations provided by this API.
#        url: http://api.example.com/docs/user-operations/
    

components:
  schemas:
  
  
    MaturityModel:
      description: |- 
        A maturity model is a set of indicators. 
        Each indicator has different levels of maturity. 
        The way indicators can be selected is defined by the type of mode
          - Unilevel, means that only one level can be selected. For example, if the for each indicator the levels of maturity are Low, Medium and High, it means that only one of them can be selected.
          - Multi level means that an indicator may have selected more than one level at a time. Which means that each level is independent. For example, if for an indicator there are two levels, such as Level A and Level B, it means that any of them can be achieved independently.
      type: object
      properties:
        code: 
          type: string
          pattern: '[a-zA-Z0-9\-\.\_]+'
          example: "MM01"
          description: "A short string identifier. Once assigned it should not be modified. It is used as external reference for the evaluation."
        name: 
          type: string
          example: "Digital Resilience Maturity Model"
        specVersion: 
          type: string
          pattern: '[0-9]\.[0-9]'
          example: 0.1
          description: "Version of the Maturiy Model Specification this model is based on. Format: Number a dot and another number"
        version: 
          type: integer
          example: 1
          description: "Numeric version of the maturity model. It is used to keep track of the compatibility."
        maturityLevels:
          description: |-
            List of the different levels of maturity the model supports. For example, Low, Medium, High or Level 1, Level 2 and Level 3.
            By default, the list should be ordered by code alphabetically.
          type: array
          items:
             $ref: "#/components/schemas/MaturityLevel"
          
        indicators:
          description: |- 
            List of the different indicators of the maturity model. 
            By default the list should be ordered by code alphabetically.
    
          type: array
          items: 
            $ref: "#/components/schemas/Indicator"  
          uniqueItems: true
        indicatorMode:
          description: "Unilevel means that only one indicator can be selected. Multilevel more than one indicator can be selected"
          type: string
          enum:
            - UniLevel
            - MultiLevel
          default: UniLevel
          nullable: true
        attributes:
          type: array
          items: 
            $ref: "#/components/schemas/ModelAttribute"  
        references: 
          type: array
          items: 
            $ref: "#/components/schemas/Reference"
       
    
    MaturityModelList:
      description: List of Maturity models
      type: array
      items:
        $ref: "#/components/schemas/MaturityModel"  
    
    
    MaturityLevel:
      description: |- 
        Each possible indicator value belongs to a level
      type: object
      properties:
        code: 
          type: string
          example: "L1"
          pattern: '[a-zA-Z0-9\-\.\_]+'
          description: "A short string identifier. Once assigned it should not be modified. It is used as external reference."
        name: 
          type: string
          example: "Level 1"
        description: 
          type: string
          example: "Lowest value"
        weight: 
          description: Weight of the level 
          type: number
          default: 1.0  
   
    
    ModelAttribute:
      description: |- 
        Attributes function as tags, labels that can be assigned to indicators. Attributes are useful to classify, categorize or filter the indicators. For example, indicators related with governance can have this attribute.
      type: object
      properties:
        code: 
          type: string
          example: "attr1"
          pattern: '[a-zA-Z0-9\-\.\_]+'
          description: "A short string identifier. Once assigned it should not be modified. It is used as external reference."
        name: 
          type: string
          example: "Analysis and design"
        description: 
          type: string
          example: "Analysis and design is the phase in which the analysis of a solution is performed."
    

    Indicator:
      description: |-
        A maturity model is a list of indicators. Each indicator has a set of levels of compliance. For example an indicator can be "Information Security Awareness training".
        A indicator belongs to a particular level. 
      type: object
      properties:
        code:
          type: string
          example: "DP-LF"
          nullable: true
        name:
          type: string
          example: "Legitimate and Fair"
        shortDescription:
          type: string
          example: |-
            As part of the business analysis, requirement decisions it is ensured that personal  data collected for the limited specified purposes has a legitimate base that supports it.
        weight: 
          type: number
          default: 1.0  
          
        indicatorMaturityLevels:
          type: array
          items:
             $ref: '#/components/schemas/IndicatorMaturityLevel'
          description: |- 
            Each indicator has a set of maturity levels, f.i. level 1, level 2, level 3.
            Each level has a description that formulates what are the requirements 
            in order to comply with it.
        attributes:
          description: "List of attributes assigned to this indicator"
          type: array
          items: 
             type: object
             properties:
              modelAttributeCode:
                type: string
                example: "attr1"
        references:
          type: array
          items:
            $ref: '#/components/schemas/Reference'
          description: |- 
           External references, links to guidance, more information, etc. 
                
    
    IndicatorMaturityLevel:
      description: |- 
        Provides a condition or a set of conditions to comply with the indicator.
        Links a maturity level with an indicator.
        For example: If there are three levels, there could be one IndicatorMaturiryLevel for each of these three levels.
      type: object
      properties: 
        indicatorCode:
          type: string
          example: "DP-LF"
          description: "Code of the indicator it is linked to"
        maturityLevelCode:
          type: string
          example: "L1"
          description: "Maturity level it is linked to" 
        description:
          type: string
          example: "In order to comply with this level on this indicator A, B and C are in place."
          description: "The description explains what are the requirements for this indicator that are evaluated to comply with this maturity level."
        references:
          type: array
          items:
            $ref: '#/components/schemas/Reference'
          description: |- 
           External references, links to guidance, more information, etc. 
           
           
    MaturityEvaluation:
      description: |-
        Defines the values of a particular instance of a model. For example, if the 
        maturity model evaluates the maturity of an application in terms of security processes and best practices, it would provide the maturiy of that especific application.
      type: object
      properties:
        id: 
          type: integer
        name: 
          description: |- 
            Name of the product/item that is going to ve evaluated against the maturity model
          type: string
        description:
          type: string
          description: "Some overall comment about the state of this evaluation"
          nullable: true
        maturityModelCode:
          type: string
          description: "Code of the maturity model"
        computedScore: 
          type: number
          description: "The overall computed score."
        selectedIndicators:
          description: |-
            List of the selected indicators. 
          type: array
          items:
            $ref: '#/components/schemas/IndicatorEvaluation'
        
    
    MaturityEvaluationList:
      type: array
      description: "List of Maturity model evaluations"
      items:
        $ref: "#/components/schemas/MaturityEvaluation"
        
    IndicatorEvaluation: 
      type: object
      properties:
        id: 
          type: integer
          format: int64
        maturityEvaluationId:
          type: integer
          format: int64
          description: "Reference to the maturity evaluation this indicator evaluation belongs to"
        indicatorCode:
          type: string
          example: "DP-LF"
          description: "The code of the indicator that is being evaluated"
        applies: 
          description: |-
            Does the indicator apply for this particular evaluation?
          type: boolean
          default: true
        comment: 
          description: |-
            Overall optional comment about the compliance with the indicator
          type: string
          nullable: true
        SelectedLevels:
          type: array
          items:
            $ref: '#/components/schemas/SelectedLevel'
          description: "What is or are the selected levels for this indicator."
          
    
    SelectedLevel:
      type: object
      description: |-
        For a particular indicator and for the evaluation of the maturity of a particular item, it represents the maturity levels that apply. 

      properties:
        maturityModelValueCode: 
          description: "Instance of a particular maturity model"
          type: string
        indicatorCode:
          description: "instance of a particular indicator in a particular maturity model"
          type: integer
          format: int64
        indicatorEvaluationId:
          description: id of the selected indicator
          type: integer
          format: int64
        isSelected:
          description: Is the level selected?
          type: boolean
          default: false
          
    Reference:
      type: object
      description: |- 
        External reference. It is useful to provide guidance and more information with regard a particular indicator.
      properties:
        name: 
          type: string
          example: More information
        url:
          type: string
          example: http://github.com/merlos/maturity-model-spec
          
